name: ci-workflow
run-name: .NET workflow CI

env:
   DOTNET_VERSION: 7.0.x

on:
  [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET $DOTNET_VERSION
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: $DOTNET_VERSION
    - name: Restore Nuget Dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
